version: '3'
services:
  xmpp_server:
    image: prosody/prosody
    ports:
      - "5222:5222"
      - "5280:5280"
      - "5281:5281"
    volumes:
      - ./conf:/etc/prosody
      - ./prosody_modules:/opt/modules
#    command: "/bin/bash /etc/prosody/init_users.sh"
volumes:
  serwer-data: