#!bin/bash
prosodyctl register user localhost user
prosodyctl register data localhost user
prosodyctl register validation localhost user
prosodyctl register knn1 localhost user
prosodyctl register knn2 localhost user
prosodyctl register knn3 localhost user
prosodyctl register knn4 localhost user
prosodyctl register knn5 localhost user
prosodyctl register knn6 localhost user
prosodyctl register knn7 localhost user
prosodyctl register knn8 localhost user
prosodyctl register knn9 localhost user
prosodyctl register knn10 localhost user
prosodyctl register knn11 localhost user
prosodyctl register knn12 localhost user
prosodyctl register knn13 localhost user
prosodyctl register knn14 localhost user
prosodyctl register knn15 localhost user
prosodyctl register knn16 localhost user
prosodyctl register knn17 localhost user
prosodyctl register knn18 localhost user
prosodyctl register knn19 localhost user
prosodyctl register knn20 localhost user
prosodyctl register knn21 localhost user
prosodyctl register knn22 localhost user
prosodyctl register knn23 localhost user
prosodyctl register knn24 localhost user
prosodyctl register knn25 localhost user
prosodyctl register knn26 localhost user
prosodyctl register knn27 localhost user
prosodyctl register knn28 localhost user
prosodyctl register knn29 localhost user
prosodyctl register knn30 localhost user
prosodyctl register knn31 localhost user
prosodyctl register knn32 localhost user
prosodyctl register knn33 localhost user
prosodyctl register knn34 localhost user
prosodyctl register knn35 localhost user
prosodyctl register knn36 localhost user
prosodyctl register knn37 localhost user
prosodyctl register knn38 localhost user
prosodyctl register knn39 localhost user
prosodyctl register knn40 localhost user
prosodyctl register knn41 localhost user
prosodyctl register knn42 localhost user
prosodyctl register knn43 localhost user
prosodyctl register knn44 localhost user
prosodyctl register knn45 localhost user
prosodyctl register knn46 localhost user
prosodyctl register knn47 localhost user
prosodyctl register knn48 localhost user
prosodyctl register knn49 localhost user
prosodyctl register knn50 localhost user
prosodyctl register knn51 localhost user
prosodyctl register knn52 localhost user
prosodyctl register knn53 localhost user
prosodyctl register knn54 localhost user
prosodyctl register knn55 localhost user
prosodyctl register knn56 localhost user
prosodyctl register knn57 localhost user
prosodyctl register knn58 localhost user
prosodyctl register knn59 localhost user
prosodyctl register knn60 localhost user